### ISSUE TITLE
[BUG] I can't log in when the mod is put up on the server

### ISSUE THREAD

**Issue by MysthZero** [ResistorCat/cobblemon-loot-balls#8]
**Important info**
- Specify mod version and cobblemon version. 
   Lootballs 1.1.4   and cobblemon fabric 1.5.2+  1.20.1

**Describe the bug**
I can't log in when the mod is put up on the server. (Look screenshot).

**Expected behavior**
I expected that I would be able to connect to the server once the mod was installed.

**Logs**

https://mclogs.minestrator.com/BOwetwN
![Capture d'écran 2024-06-16 212251](https://github.com/ResistorCat/cobblemon-loot-balls/assets/173007737/cf83f73f-14ee-4af5-81e0-e2c948c99f52)

**Comment by ResistorCat** [comment]
Hi!, can you provide your client logs? The server log seems good to me.

**Comment by MysthZero** [comment]
Yeah sure !

https://mclogs.minestrator.com/UBw1nZa

**Comment by ResistorCat** [comment]
It seems like lootballs mod isn't loading properly in your client. Do you have the same mod versión on both client and server? If so, can you provide me the logs of client initialization (what appears on the client console when opening a minecraft instance and the client starts loading the mods).

**Comment by ResistorCat** [comment]
If you read the first logs when loading, in some lines it should say something like "registering blocks for lootballs"

**Comment by ResistorCat** [comment]
Hi, I'm closing this issue as it has been a while without new information to address the problem. If you need more help you can open a new issue.
